services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - shared_network
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["python", "app.py"]

networks:
  shared_network:
    external: true
