services:
  db:
    image: postgres:latest
    container_name: postgres_db
    hostname: postgres_db
    networks:
      - shared_network
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d 
volumes:
  db_data:

networks:
  shared_network:
    external: true